/* File: aftanmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Aug 10 22:51:45 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *aftan_error;
static PyObject *aftan_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef struct {double r,i;} complex_double;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(aftan_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = aftan_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = aftan_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(aftanipg,AFTANIPG)(double*,int*,float*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,double*,int*,double*,double*,int*,int*,int*,double*,double*,float*,int*,double*,int*,double*,double*,int*,int*,double*,int*);
extern void F_FUNC_US(unknown_subroutine,UNKNOWN_SUBROUTINE)(void);
extern void F_FUNC(fmax,FMAX)(double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*);
extern void F_FUNC(ftfilt,FTFILT)(double*,double*,double*,int*,complex_double*,complex_double*,double*);
extern void F_FUNC(mspline,MSPLINE)(int*,int*,double*,double*,int*,double*,int*,double*);
extern void F_FUNC(msplint,MSPLINT)(int*,double*,double*,double*,int*);
extern void F_FUNC(msplder,MSPLDER)(int*,double*,double*,double*,double*,int*);
extern void F_FUNC(cubspl,CUBSPL)(double*,double*,int*,int*,int*);
extern void F_FUNC(phtovel,PHTOVEL)(double*,int*,int*,double*,double*,double*,int*,double*,double*,double*);
extern void F_FUNC_US(pred_cur,PRED_CUR)(int*,double*,double*,int*,double*,double*,double*);
extern void F_FUNC(taper,TAPER)(int*,int*,int*,float*,int*,int*,complex_double*,int*);
extern void F_FUNC(tapers,TAPERS)(double*,double*,double*,double*,int*,double*,int*,int*,double*,double*);
extern void F_FUNC(tgauss,TGAUSS)(double*,double*,double*,double*,double*,int*,double*,complex_double*,complex_double*,int*);
extern void F_FUNC(trigger,TRIGGER)(double*,double*,int*,double*,double*,double*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** aftanipg **********************************/
static char doc_f2py_rout_aftan_aftanipg[] = "\
aftanipg(piover4,n,sei,t0,dt,delta,vmin,vmax,tmin,tmax,tresh,ffact,perc,npoints,taperl,nfin,fsnr,fmatch,npred,cuttype,phprper,phprvel,seiout,nfout1,arr1,nfout2,arr2,tamp,nrow,ncol,amp,ierr,[nphpr])\n\nWrapper for ``aftanipg``.\
\n\nParameters\n----------\n"
"piover4 : input float\n"
"n : input int\n"
"sei : input rank-1 array('f') with bounds (32768)\n"
"t0 : input float\n"
"dt : input float\n"
"delta : input float\n"
"vmin : input float\n"
"vmax : input float\n"
"tmin : input float\n"
"tmax : input float\n"
"tresh : input float\n"
"ffact : input float\n"
"perc : input float\n"
"npoints : input int\n"
"taperl : input float\n"
"nfin : input int\n"
"fsnr : input float\n"
"fmatch : input float\n"
"npred : input int\n"
"cuttype : input int\n"
"phprper : input rank-1 array('d') with bounds (nphpr)\n"
"phprvel : input rank-1 array('d') with bounds (nphpr)\n"
"seiout : input rank-1 array('f') with bounds (32768)\n"
"nfout1 : input int\n"
"arr1 : input rank-2 array('d') with bounds (8,100)\n"
"nfout2 : input int\n"
"arr2 : input rank-2 array('d') with bounds (7,100)\n"
"tamp : input float\n"
"nrow : input int\n"
"ncol : input int\n"
"amp : input rank-2 array('d') with bounds (32768,32)\n"
"ierr : input int\n"
"\nOther Parameters\n----------------\n"
"nphpr : input int, optional\n    Default: len(phprper)";
/* extern void F_FUNC(aftanipg,AFTANIPG)(double*,int*,float*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,double*,int*,double*,double*,int*,int*,int*,double*,double*,float*,int*,double*,int*,double*,double*,int*,int*,double*,int*); */
static PyObject *f2py_rout_aftan_aftanipg(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,float*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,double*,int*,double*,double*,int*,int*,int*,double*,double*,float*,int*,double*,int*,double*,double*,int*,int*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double piover4 = 0;
  PyObject *piover4_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  float *sei = NULL;
  npy_intp sei_Dims[1] = {-1};
  const int sei_Rank = 1;
  PyArrayObject *capi_sei_tmp = NULL;
  int capi_sei_intent = 0;
  PyObject *sei_capi = Py_None;
  double t0 = 0;
  PyObject *t0_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  double delta = 0;
  PyObject *delta_capi = Py_None;
  double vmin = 0;
  PyObject *vmin_capi = Py_None;
  double vmax = 0;
  PyObject *vmax_capi = Py_None;
  double tmin = 0;
  PyObject *tmin_capi = Py_None;
  double tmax = 0;
  PyObject *tmax_capi = Py_None;
  double tresh = 0;
  PyObject *tresh_capi = Py_None;
  double ffact = 0;
  PyObject *ffact_capi = Py_None;
  double perc = 0;
  PyObject *perc_capi = Py_None;
  int npoints = 0;
  PyObject *npoints_capi = Py_None;
  double taperl = 0;
  PyObject *taperl_capi = Py_None;
  int nfin = 0;
  PyObject *nfin_capi = Py_None;
  double fsnr = 0;
  PyObject *fsnr_capi = Py_None;
  double fmatch = 0;
  PyObject *fmatch_capi = Py_None;
  int npred = 0;
  PyObject *npred_capi = Py_None;
  int cuttype = 0;
  PyObject *cuttype_capi = Py_None;
  int nphpr = 0;
  PyObject *nphpr_capi = Py_None;
  double *phprper = NULL;
  npy_intp phprper_Dims[1] = {-1};
  const int phprper_Rank = 1;
  PyArrayObject *capi_phprper_tmp = NULL;
  int capi_phprper_intent = 0;
  PyObject *phprper_capi = Py_None;
  double *phprvel = NULL;
  npy_intp phprvel_Dims[1] = {-1};
  const int phprvel_Rank = 1;
  PyArrayObject *capi_phprvel_tmp = NULL;
  int capi_phprvel_intent = 0;
  PyObject *phprvel_capi = Py_None;
  float *seiout = NULL;
  npy_intp seiout_Dims[1] = {-1};
  const int seiout_Rank = 1;
  PyArrayObject *capi_seiout_tmp = NULL;
  int capi_seiout_intent = 0;
  PyObject *seiout_capi = Py_None;
  int nfout1 = 0;
  PyObject *nfout1_capi = Py_None;
  double *arr1 = NULL;
  npy_intp arr1_Dims[2] = {-1, -1};
  const int arr1_Rank = 2;
  PyArrayObject *capi_arr1_tmp = NULL;
  int capi_arr1_intent = 0;
  PyObject *arr1_capi = Py_None;
  int nfout2 = 0;
  PyObject *nfout2_capi = Py_None;
  double *arr2 = NULL;
  npy_intp arr2_Dims[2] = {-1, -1};
  const int arr2_Rank = 2;
  PyArrayObject *capi_arr2_tmp = NULL;
  int capi_arr2_intent = 0;
  PyObject *arr2_capi = Py_None;
  double tamp = 0;
  PyObject *tamp_capi = Py_None;
  int nrow = 0;
  PyObject *nrow_capi = Py_None;
  int ncol = 0;
  PyObject *ncol_capi = Py_None;
  double *amp = NULL;
  npy_intp amp_Dims[2] = {-1, -1};
  const int amp_Rank = 2;
  PyArrayObject *capi_amp_tmp = NULL;
  int capi_amp_intent = 0;
  PyObject *amp_capi = Py_None;
  int ierr = 0;
  PyObject *ierr_capi = Py_None;
  static char *capi_kwlist[] = {"piover4","n","sei","t0","dt","delta","vmin","vmax","tmin","tmax","tresh","ffact","perc","npoints","taperl","nfin","fsnr","fmatch","npred","cuttype","phprper","phprvel","seiout","nfout1","arr1","nfout2","arr2","tamp","nrow","ncol","amp","ierr","nphpr",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|O:aftan.aftanipg",\
    capi_kwlist,&piover4_capi,&n_capi,&sei_capi,&t0_capi,&dt_capi,&delta_capi,&vmin_capi,&vmax_capi,&tmin_capi,&tmax_capi,&tresh_capi,&ffact_capi,&perc_capi,&npoints_capi,&taperl_capi,&nfin_capi,&fsnr_capi,&fmatch_capi,&npred_capi,&cuttype_capi,&phprper_capi,&phprvel_capi,&seiout_capi,&nfout1_capi,&arr1_capi,&nfout2_capi,&arr2_capi,&tamp_capi,&nrow_capi,&ncol_capi,&amp_capi,&ierr_capi,&nphpr_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"aftan.aftanipg() 2nd argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable npoints */
    f2py_success = int_from_pyobj(&npoints,npoints_capi,"aftan.aftanipg() 14th argument (npoints) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nfin */
    f2py_success = int_from_pyobj(&nfin,nfin_capi,"aftan.aftanipg() 16th argument (nfin) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nfout1 */
    f2py_success = int_from_pyobj(&nfout1,nfout1_capi,"aftan.aftanipg() 24th argument (nfout1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ierr */
    f2py_success = int_from_pyobj(&ierr,ierr_capi,"aftan.aftanipg() 32nd argument (ierr) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nrow */
    f2py_success = int_from_pyobj(&nrow,nrow_capi,"aftan.aftanipg() 29th argument (nrow) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ncol */
    f2py_success = int_from_pyobj(&ncol,ncol_capi,"aftan.aftanipg() 30th argument (ncol) can't be converted to int");
  if (f2py_success) {
  /* Processing variable cuttype */
    f2py_success = int_from_pyobj(&cuttype,cuttype_capi,"aftan.aftanipg() 20th argument (cuttype) can't be converted to int");
  if (f2py_success) {
  /* Processing variable piover4 */
    f2py_success = double_from_pyobj(&piover4,piover4_capi,"aftan.aftanipg() 1st argument (piover4) can't be converted to double");
  if (f2py_success) {
  /* Processing variable perc */
    f2py_success = double_from_pyobj(&perc,perc_capi,"aftan.aftanipg() 13rd argument (perc) can't be converted to double");
  if (f2py_success) {
  /* Processing variable taperl */
    f2py_success = double_from_pyobj(&taperl,taperl_capi,"aftan.aftanipg() 15th argument (taperl) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tamp */
    f2py_success = double_from_pyobj(&tamp,tamp_capi,"aftan.aftanipg() 28th argument (tamp) can't be converted to double");
  if (f2py_success) {
  /* Processing variable arr1 */
  arr1_Dims[0]=8,arr1_Dims[1]=100;
  capi_arr1_intent |= F2PY_INTENT_IN;
  capi_arr1_tmp = array_from_pyobj(NPY_DOUBLE,arr1_Dims,arr1_Rank,capi_arr1_intent,arr1_capi);
  if (capi_arr1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 25th argument `arr1' of aftan.aftanipg to C/Fortran array" );
  } else {
    arr1 = (double *)(PyArray_DATA(capi_arr1_tmp));

  /* Processing variable arr2 */
  arr2_Dims[0]=7,arr2_Dims[1]=100;
  capi_arr2_intent |= F2PY_INTENT_IN;
  capi_arr2_tmp = array_from_pyobj(NPY_DOUBLE,arr2_Dims,arr2_Rank,capi_arr2_intent,arr2_capi);
  if (capi_arr2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 27th argument `arr2' of aftan.aftanipg to C/Fortran array" );
  } else {
    arr2 = (double *)(PyArray_DATA(capi_arr2_tmp));

  /* Processing variable t0 */
    f2py_success = double_from_pyobj(&t0,t0_capi,"aftan.aftanipg() 4th argument (t0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"aftan.aftanipg() 5th argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable delta */
    f2py_success = double_from_pyobj(&delta,delta_capi,"aftan.aftanipg() 6th argument (delta) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vmin */
    f2py_success = double_from_pyobj(&vmin,vmin_capi,"aftan.aftanipg() 7th argument (vmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vmax */
    f2py_success = double_from_pyobj(&vmax,vmax_capi,"aftan.aftanipg() 8th argument (vmax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tmin */
    f2py_success = double_from_pyobj(&tmin,tmin_capi,"aftan.aftanipg() 9th argument (tmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tmax */
    f2py_success = double_from_pyobj(&tmax,tmax_capi,"aftan.aftanipg() 10th argument (tmax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tresh */
    f2py_success = double_from_pyobj(&tresh,tresh_capi,"aftan.aftanipg() 11st argument (tresh) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ffact */
    f2py_success = double_from_pyobj(&ffact,ffact_capi,"aftan.aftanipg() 12nd argument (ffact) can't be converted to double");
  if (f2py_success) {
  /* Processing variable fsnr */
    f2py_success = double_from_pyobj(&fsnr,fsnr_capi,"aftan.aftanipg() 17th argument (fsnr) can't be converted to double");
  if (f2py_success) {
  /* Processing variable fmatch */
    f2py_success = double_from_pyobj(&fmatch,fmatch_capi,"aftan.aftanipg() 18th argument (fmatch) can't be converted to double");
  if (f2py_success) {
  /* Processing variable sei */
  sei_Dims[0]=32768;
  capi_sei_intent |= F2PY_INTENT_IN;
  capi_sei_tmp = array_from_pyobj(NPY_FLOAT,sei_Dims,sei_Rank,capi_sei_intent,sei_capi);
  if (capi_sei_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 3rd argument `sei' of aftan.aftanipg to C/Fortran array" );
  } else {
    sei = (float *)(PyArray_DATA(capi_sei_tmp));

  /* Processing variable seiout */
  seiout_Dims[0]=32768;
  capi_seiout_intent |= F2PY_INTENT_IN;
  capi_seiout_tmp = array_from_pyobj(NPY_FLOAT,seiout_Dims,seiout_Rank,capi_seiout_intent,seiout_capi);
  if (capi_seiout_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 23rd argument `seiout' of aftan.aftanipg to C/Fortran array" );
  } else {
    seiout = (float *)(PyArray_DATA(capi_seiout_tmp));

  /* Processing variable amp */
  amp_Dims[0]=32768,amp_Dims[1]=32;
  capi_amp_intent |= F2PY_INTENT_IN;
  capi_amp_tmp = array_from_pyobj(NPY_DOUBLE,amp_Dims,amp_Rank,capi_amp_intent,amp_capi);
  if (capi_amp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 31st argument `amp' of aftan.aftanipg to C/Fortran array" );
  } else {
    amp = (double *)(PyArray_DATA(capi_amp_tmp));

  /* Processing variable nfout2 */
    f2py_success = int_from_pyobj(&nfout2,nfout2_capi,"aftan.aftanipg() 26th argument (nfout2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable phprper */
  ;
  capi_phprper_intent |= F2PY_INTENT_IN;
  capi_phprper_tmp = array_from_pyobj(NPY_DOUBLE,phprper_Dims,phprper_Rank,capi_phprper_intent,phprper_capi);
  if (capi_phprper_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 21st argument `phprper' of aftan.aftanipg to C/Fortran array" );
  } else {
    phprper = (double *)(PyArray_DATA(capi_phprper_tmp));

  /* Processing variable npred */
    f2py_success = int_from_pyobj(&npred,npred_capi,"aftan.aftanipg() 19th argument (npred) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nphpr */
  if (nphpr_capi == Py_None) nphpr = len(phprper); else
    f2py_success = int_from_pyobj(&nphpr,nphpr_capi,"aftan.aftanipg() 1st keyword (nphpr) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(phprper)>=nphpr,"len(phprper)>=nphpr","1st keyword nphpr","aftanipg:nphpr=%d",nphpr) {
  /* Processing variable phprvel */
  phprvel_Dims[0]=nphpr;
  capi_phprvel_intent |= F2PY_INTENT_IN;
  capi_phprvel_tmp = array_from_pyobj(NPY_DOUBLE,phprvel_Dims,phprvel_Rank,capi_phprvel_intent,phprvel_capi);
  if (capi_phprvel_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 22nd argument `phprvel' of aftan.aftanipg to C/Fortran array" );
  } else {
    phprvel = (double *)(PyArray_DATA(capi_phprvel_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&piover4,&n,sei,&t0,&dt,&delta,&vmin,&vmax,&tmin,&tmax,&tresh,&ffact,&perc,&npoints,&taperl,&nfin,&fsnr,&fmatch,&npred,&cuttype,&nphpr,phprper,phprvel,seiout,&nfout1,arr1,&nfout2,arr2,&tamp,&nrow,&ncol,amp,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_phprvel_tmp!=phprvel_capi) {
    Py_XDECREF(capi_phprvel_tmp); }
  }  /*if (capi_phprvel_tmp == NULL) ... else of phprvel*/
  /* End of cleaning variable phprvel */
  } /*CHECKSCALAR(len(phprper)>=nphpr)*/
  } /*if (f2py_success) of nphpr*/
  /* End of cleaning variable nphpr */
  } /*if (f2py_success) of npred*/
  /* End of cleaning variable npred */
  if((PyObject *)capi_phprper_tmp!=phprper_capi) {
    Py_XDECREF(capi_phprper_tmp); }
  }  /*if (capi_phprper_tmp == NULL) ... else of phprper*/
  /* End of cleaning variable phprper */
  } /*if (f2py_success) of nfout2*/
  /* End of cleaning variable nfout2 */
  if((PyObject *)capi_amp_tmp!=amp_capi) {
    Py_XDECREF(capi_amp_tmp); }
  }  /*if (capi_amp_tmp == NULL) ... else of amp*/
  /* End of cleaning variable amp */
  if((PyObject *)capi_seiout_tmp!=seiout_capi) {
    Py_XDECREF(capi_seiout_tmp); }
  }  /*if (capi_seiout_tmp == NULL) ... else of seiout*/
  /* End of cleaning variable seiout */
  if((PyObject *)capi_sei_tmp!=sei_capi) {
    Py_XDECREF(capi_sei_tmp); }
  }  /*if (capi_sei_tmp == NULL) ... else of sei*/
  /* End of cleaning variable sei */
  } /*if (f2py_success) of fmatch*/
  /* End of cleaning variable fmatch */
  } /*if (f2py_success) of fsnr*/
  /* End of cleaning variable fsnr */
  } /*if (f2py_success) of ffact*/
  /* End of cleaning variable ffact */
  } /*if (f2py_success) of tresh*/
  /* End of cleaning variable tresh */
  } /*if (f2py_success) of tmax*/
  /* End of cleaning variable tmax */
  } /*if (f2py_success) of tmin*/
  /* End of cleaning variable tmin */
  } /*if (f2py_success) of vmax*/
  /* End of cleaning variable vmax */
  } /*if (f2py_success) of vmin*/
  /* End of cleaning variable vmin */
  } /*if (f2py_success) of delta*/
  /* End of cleaning variable delta */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  } /*if (f2py_success) of t0*/
  /* End of cleaning variable t0 */
  if((PyObject *)capi_arr2_tmp!=arr2_capi) {
    Py_XDECREF(capi_arr2_tmp); }
  }  /*if (capi_arr2_tmp == NULL) ... else of arr2*/
  /* End of cleaning variable arr2 */
  if((PyObject *)capi_arr1_tmp!=arr1_capi) {
    Py_XDECREF(capi_arr1_tmp); }
  }  /*if (capi_arr1_tmp == NULL) ... else of arr1*/
  /* End of cleaning variable arr1 */
  } /*if (f2py_success) of tamp*/
  /* End of cleaning variable tamp */
  } /*if (f2py_success) of taperl*/
  /* End of cleaning variable taperl */
  } /*if (f2py_success) of perc*/
  /* End of cleaning variable perc */
  } /*if (f2py_success) of piover4*/
  /* End of cleaning variable piover4 */
  } /*if (f2py_success) of cuttype*/
  /* End of cleaning variable cuttype */
  } /*if (f2py_success) of ncol*/
  /* End of cleaning variable ncol */
  } /*if (f2py_success) of nrow*/
  /* End of cleaning variable nrow */
  } /*if (f2py_success) of ierr*/
  /* End of cleaning variable ierr */
  } /*if (f2py_success) of nfout1*/
  /* End of cleaning variable nfout1 */
  } /*if (f2py_success) of nfin*/
  /* End of cleaning variable nfin */
  } /*if (f2py_success) of npoints*/
  /* End of cleaning variable npoints */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of aftanipg ******************************/

/***************************** unknown_subroutine *****************************/
static char doc_f2py_rout_aftan_unknown_subroutine[] = "\
unknown_subroutine()\n\nWrapper for ``unknown_subroutine``.\
\n";
/* extern void F_FUNC_US(unknown_subroutine,UNKNOWN_SUBROUTINE)(void); */
static PyObject *f2py_rout_aftan_unknown_subroutine(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":aftan.unknown_subroutine",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************* end of unknown_subroutine *************************/

/************************************ fmax ************************************/
static char doc_f2py_rout_aftan_fmax[] = "\
fmax(am1,am2,am3,ph1,ph2,ph3,om,dt,t,dph,tm,ph,piover4)\n\nWrapper for ``fmax``.\
\n\nParameters\n----------\n"
"am1 : input float\n"
"am2 : input float\n"
"am3 : input float\n"
"ph1 : input float\n"
"ph2 : input float\n"
"ph3 : input float\n"
"om : input float\n"
"dt : input float\n"
"t : input float\n"
"dph : input float\n"
"tm : input float\n"
"ph : input float\n"
"piover4 : input float";
/* extern void F_FUNC(fmax,FMAX)(double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_aftan_fmax(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double am1 = 0;
  PyObject *am1_capi = Py_None;
  double am2 = 0;
  PyObject *am2_capi = Py_None;
  double am3 = 0;
  PyObject *am3_capi = Py_None;
  double ph1 = 0;
  PyObject *ph1_capi = Py_None;
  double ph2 = 0;
  PyObject *ph2_capi = Py_None;
  double ph3 = 0;
  PyObject *ph3_capi = Py_None;
  double om = 0;
  PyObject *om_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  double t = 0;
  PyObject *t_capi = Py_None;
  double dph = 0;
  PyObject *dph_capi = Py_None;
  double tm = 0;
  PyObject *tm_capi = Py_None;
  double ph = 0;
  PyObject *ph_capi = Py_None;
  double piover4 = 0;
  PyObject *piover4_capi = Py_None;
  static char *capi_kwlist[] = {"am1","am2","am3","ph1","ph2","ph3","om","dt","t","dph","tm","ph","piover4",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOO:aftan.fmax",\
    capi_kwlist,&am1_capi,&am2_capi,&am3_capi,&ph1_capi,&ph2_capi,&ph3_capi,&om_capi,&dt_capi,&t_capi,&dph_capi,&tm_capi,&ph_capi,&piover4_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable t */
    f2py_success = double_from_pyobj(&t,t_capi,"aftan.fmax() 9th argument (t) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dph */
    f2py_success = double_from_pyobj(&dph,dph_capi,"aftan.fmax() 10th argument (dph) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tm */
    f2py_success = double_from_pyobj(&tm,tm_capi,"aftan.fmax() 11st argument (tm) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ph1 */
    f2py_success = double_from_pyobj(&ph1,ph1_capi,"aftan.fmax() 4th argument (ph1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ph2 */
    f2py_success = double_from_pyobj(&ph2,ph2_capi,"aftan.fmax() 5th argument (ph2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ph3 */
    f2py_success = double_from_pyobj(&ph3,ph3_capi,"aftan.fmax() 6th argument (ph3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ph */
    f2py_success = double_from_pyobj(&ph,ph_capi,"aftan.fmax() 12nd argument (ph) can't be converted to double");
  if (f2py_success) {
  /* Processing variable om */
    f2py_success = double_from_pyobj(&om,om_capi,"aftan.fmax() 7th argument (om) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"aftan.fmax() 8th argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable am1 */
    f2py_success = double_from_pyobj(&am1,am1_capi,"aftan.fmax() 1st argument (am1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable am2 */
    f2py_success = double_from_pyobj(&am2,am2_capi,"aftan.fmax() 2nd argument (am2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable am3 */
    f2py_success = double_from_pyobj(&am3,am3_capi,"aftan.fmax() 3rd argument (am3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable piover4 */
    f2py_success = double_from_pyobj(&piover4,piover4_capi,"aftan.fmax() 13rd argument (piover4) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&am1,&am2,&am3,&ph1,&ph2,&ph3,&om,&dt,&t,&dph,&tm,&ph,&piover4);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of piover4*/
  /* End of cleaning variable piover4 */
  } /*if (f2py_success) of am3*/
  /* End of cleaning variable am3 */
  } /*if (f2py_success) of am2*/
  /* End of cleaning variable am2 */
  } /*if (f2py_success) of am1*/
  /* End of cleaning variable am1 */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  } /*if (f2py_success) of om*/
  /* End of cleaning variable om */
  } /*if (f2py_success) of ph*/
  /* End of cleaning variable ph */
  } /*if (f2py_success) of ph3*/
  /* End of cleaning variable ph3 */
  } /*if (f2py_success) of ph2*/
  /* End of cleaning variable ph2 */
  } /*if (f2py_success) of ph1*/
  /* End of cleaning variable ph1 */
  } /*if (f2py_success) of tm*/
  /* End of cleaning variable tm */
  } /*if (f2py_success) of dph*/
  /* End of cleaning variable dph */
  } /*if (f2py_success) of t*/
  /* End of cleaning variable t */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of fmax ********************************/

/*********************************** ftfilt ***********************************/
static char doc_f2py_rout_aftan_ftfilt[] = "\
ftfilt(alpha,om0,dom,n,a,fs,b)\n\nWrapper for ``ftfilt``.\
\n\nParameters\n----------\n"
"alpha : input float\n"
"om0 : input float\n"
"dom : input float\n"
"n : input int\n"
"a : input rank-1 array('D') with bounds (32768)\n"
"fs : input rank-1 array('D') with bounds (32768)\n"
"b : input rank-1 array('d') with bounds (32768)";
/* extern void F_FUNC(ftfilt,FTFILT)(double*,double*,double*,int*,complex_double*,complex_double*,double*); */
static PyObject *f2py_rout_aftan_ftfilt(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*,complex_double*,complex_double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double alpha = 0;
  PyObject *alpha_capi = Py_None;
  double om0 = 0;
  PyObject *om0_capi = Py_None;
  double dom = 0;
  PyObject *dom_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  complex_double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  complex_double *fs = NULL;
  npy_intp fs_Dims[1] = {-1};
  const int fs_Rank = 1;
  PyArrayObject *capi_fs_tmp = NULL;
  int capi_fs_intent = 0;
  PyObject *fs_capi = Py_None;
  double *b = NULL;
  npy_intp b_Dims[1] = {-1};
  const int b_Rank = 1;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  static char *capi_kwlist[] = {"alpha","om0","dom","n","a","fs","b",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:aftan.ftfilt",\
    capi_kwlist,&alpha_capi,&om0_capi,&dom_capi,&n_capi,&a_capi,&fs_capi,&b_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"aftan.ftfilt() 4th argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable alpha */
    f2py_success = double_from_pyobj(&alpha,alpha_capi,"aftan.ftfilt() 1st argument (alpha) can't be converted to double");
  if (f2py_success) {
  /* Processing variable om0 */
    f2py_success = double_from_pyobj(&om0,om0_capi,"aftan.ftfilt() 2nd argument (om0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dom */
    f2py_success = double_from_pyobj(&dom,dom_capi,"aftan.ftfilt() 3rd argument (dom) can't be converted to double");
  if (f2py_success) {
  /* Processing variable b */
  b_Dims[0]=32768;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(NPY_DOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 7th argument `b' of aftan.ftfilt to C/Fortran array" );
  } else {
    b = (double *)(PyArray_DATA(capi_b_tmp));

  /* Processing variable a */
  a_Dims[0]=32768;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_CDOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 5th argument `a' of aftan.ftfilt to C/Fortran array" );
  } else {
    a = (complex_double *)(PyArray_DATA(capi_a_tmp));

  /* Processing variable fs */
  fs_Dims[0]=32768;
  capi_fs_intent |= F2PY_INTENT_IN;
  capi_fs_tmp = array_from_pyobj(NPY_CDOUBLE,fs_Dims,fs_Rank,capi_fs_intent,fs_capi);
  if (capi_fs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 6th argument `fs' of aftan.ftfilt to C/Fortran array" );
  } else {
    fs = (complex_double *)(PyArray_DATA(capi_fs_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&alpha,&om0,&dom,&n,a,fs,b);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_fs_tmp!=fs_capi) {
    Py_XDECREF(capi_fs_tmp); }
  }  /*if (capi_fs_tmp == NULL) ... else of fs*/
  /* End of cleaning variable fs */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  } /*if (f2py_success) of dom*/
  /* End of cleaning variable dom */
  } /*if (f2py_success) of om0*/
  /* End of cleaning variable om0 */
  } /*if (f2py_success) of alpha*/
  /* End of cleaning variable alpha */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of ftfilt *******************************/

/********************************** mspline **********************************/
static char doc_f2py_rout_aftan_mspline[] = "\
mspline(ip,n,x,y,ind1,d1,ind2,d2)\n\nWrapper for ``mspline``.\
\n\nParameters\n----------\n"
"ip : input int\n"
"n : input int\n"
"x : input rank-1 array('d') with bounds (1001)\n"
"y : input rank-1 array('d') with bounds (1001)\n"
"ind1 : input int\n"
"d1 : input float\n"
"ind2 : input int\n"
"d2 : input float";
/* extern void F_FUNC(mspline,MSPLINE)(int*,int*,double*,double*,int*,double*,int*,double*); */
static PyObject *f2py_rout_aftan_mspline(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,int*,double*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int ip = 0;
  PyObject *ip_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int ind1 = 0;
  PyObject *ind1_capi = Py_None;
  double d1 = 0;
  PyObject *d1_capi = Py_None;
  int ind2 = 0;
  PyObject *ind2_capi = Py_None;
  double d2 = 0;
  PyObject *d2_capi = Py_None;
  static char *capi_kwlist[] = {"ip","n","x","y","ind1","d1","ind2","d2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO:aftan.mspline",\
    capi_kwlist,&ip_capi,&n_capi,&x_capi,&y_capi,&ind1_capi,&d1_capi,&ind2_capi,&d2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable x */
  x_Dims[0]=1001;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 3rd argument `x' of aftan.mspline to C/Fortran array" );
  } else {
    x = (double *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable y */
  y_Dims[0]=1001;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 4th argument `y' of aftan.mspline to C/Fortran array" );
  } else {
    y = (double *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable ip */
    f2py_success = int_from_pyobj(&ip,ip_capi,"aftan.mspline() 1st argument (ip) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"aftan.mspline() 2nd argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ind1 */
    f2py_success = int_from_pyobj(&ind1,ind1_capi,"aftan.mspline() 5th argument (ind1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ind2 */
    f2py_success = int_from_pyobj(&ind2,ind2_capi,"aftan.mspline() 7th argument (ind2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable d1 */
    f2py_success = double_from_pyobj(&d1,d1_capi,"aftan.mspline() 6th argument (d1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable d2 */
    f2py_success = double_from_pyobj(&d2,d2_capi,"aftan.mspline() 8th argument (d2) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&ip,&n,x,y,&ind1,&d1,&ind2,&d2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of d2*/
  /* End of cleaning variable d2 */
  } /*if (f2py_success) of d1*/
  /* End of cleaning variable d1 */
  } /*if (f2py_success) of ind2*/
  /* End of cleaning variable ind2 */
  } /*if (f2py_success) of ind1*/
  /* End of cleaning variable ind1 */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of ip*/
  /* End of cleaning variable ip */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of mspline *******************************/

/********************************** msplint **********************************/
static char doc_f2py_rout_aftan_msplint[] = "\
msplint(ip,sa,sb,sint,ierr)\n\nWrapper for ``msplint``.\
\n\nParameters\n----------\n"
"ip : input int\n"
"sa : input float\n"
"sb : input float\n"
"sint : input float\n"
"ierr : input int";
/* extern void F_FUNC(msplint,MSPLINT)(int*,double*,double*,double*,int*); */
static PyObject *f2py_rout_aftan_msplint(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int ip = 0;
  PyObject *ip_capi = Py_None;
  double sa = 0;
  PyObject *sa_capi = Py_None;
  double sb = 0;
  PyObject *sb_capi = Py_None;
  double sint = 0;
  PyObject *sint_capi = Py_None;
  int ierr = 0;
  PyObject *ierr_capi = Py_None;
  static char *capi_kwlist[] = {"ip","sa","sb","sint","ierr",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO:aftan.msplint",\
    capi_kwlist,&ip_capi,&sa_capi,&sb_capi,&sint_capi,&ierr_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ip */
    f2py_success = int_from_pyobj(&ip,ip_capi,"aftan.msplint() 1st argument (ip) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ierr */
    f2py_success = int_from_pyobj(&ierr,ierr_capi,"aftan.msplint() 5th argument (ierr) can't be converted to int");
  if (f2py_success) {
  /* Processing variable sa */
    f2py_success = double_from_pyobj(&sa,sa_capi,"aftan.msplint() 2nd argument (sa) can't be converted to double");
  if (f2py_success) {
  /* Processing variable sb */
    f2py_success = double_from_pyobj(&sb,sb_capi,"aftan.msplint() 3rd argument (sb) can't be converted to double");
  if (f2py_success) {
  /* Processing variable sint */
    f2py_success = double_from_pyobj(&sint,sint_capi,"aftan.msplint() 4th argument (sint) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&ip,&sa,&sb,&sint,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of sint*/
  /* End of cleaning variable sint */
  } /*if (f2py_success) of sb*/
  /* End of cleaning variable sb */
  } /*if (f2py_success) of sa*/
  /* End of cleaning variable sa */
  } /*if (f2py_success) of ierr*/
  /* End of cleaning variable ierr */
  } /*if (f2py_success) of ip*/
  /* End of cleaning variable ip */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of msplint *******************************/

/********************************** msplder **********************************/
static char doc_f2py_rout_aftan_msplder[] = "\
msplder(ip,xt,s,sd,sdd,ierr)\n\nWrapper for ``msplder``.\
\n\nParameters\n----------\n"
"ip : input int\n"
"xt : input float\n"
"s : input float\n"
"sd : input float\n"
"sdd : input float\n"
"ierr : input int";
/* extern void F_FUNC(msplder,MSPLDER)(int*,double*,double*,double*,double*,int*); */
static PyObject *f2py_rout_aftan_msplder(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int ip = 0;
  PyObject *ip_capi = Py_None;
  double xt = 0;
  PyObject *xt_capi = Py_None;
  double s = 0;
  PyObject *s_capi = Py_None;
  double sd = 0;
  PyObject *sd_capi = Py_None;
  double sdd = 0;
  PyObject *sdd_capi = Py_None;
  int ierr = 0;
  PyObject *ierr_capi = Py_None;
  static char *capi_kwlist[] = {"ip","xt","s","sd","sdd","ierr",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:aftan.msplder",\
    capi_kwlist,&ip_capi,&xt_capi,&s_capi,&sd_capi,&sdd_capi,&ierr_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ip */
    f2py_success = int_from_pyobj(&ip,ip_capi,"aftan.msplder() 1st argument (ip) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ierr */
    f2py_success = int_from_pyobj(&ierr,ierr_capi,"aftan.msplder() 6th argument (ierr) can't be converted to int");
  if (f2py_success) {
  /* Processing variable xt */
    f2py_success = double_from_pyobj(&xt,xt_capi,"aftan.msplder() 2nd argument (xt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable s */
    f2py_success = double_from_pyobj(&s,s_capi,"aftan.msplder() 3rd argument (s) can't be converted to double");
  if (f2py_success) {
  /* Processing variable sd */
    f2py_success = double_from_pyobj(&sd,sd_capi,"aftan.msplder() 4th argument (sd) can't be converted to double");
  if (f2py_success) {
  /* Processing variable sdd */
    f2py_success = double_from_pyobj(&sdd,sdd_capi,"aftan.msplder() 5th argument (sdd) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&ip,&xt,&s,&sd,&sdd,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of sdd*/
  /* End of cleaning variable sdd */
  } /*if (f2py_success) of sd*/
  /* End of cleaning variable sd */
  } /*if (f2py_success) of s*/
  /* End of cleaning variable s */
  } /*if (f2py_success) of xt*/
  /* End of cleaning variable xt */
  } /*if (f2py_success) of ierr*/
  /* End of cleaning variable ierr */
  } /*if (f2py_success) of ip*/
  /* End of cleaning variable ip */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of msplder *******************************/

/*********************************** cubspl ***********************************/
static char doc_f2py_rout_aftan_cubspl[] = "\
cubspl(tau,c,ibcbeg,ibcend,[n])\n\nWrapper for ``cubspl``.\
\n\nParameters\n----------\n"
"tau : input rank-1 array('d') with bounds (n)\n"
"c : input rank-2 array('d') with bounds (4,n)\n"
"ibcbeg : input int\n"
"ibcend : input int\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(tau)";
/* extern void F_FUNC(cubspl,CUBSPL)(double*,double*,int*,int*,int*); */
static PyObject *f2py_rout_aftan_cubspl(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *tau = NULL;
  npy_intp tau_Dims[1] = {-1};
  const int tau_Rank = 1;
  PyArrayObject *capi_tau_tmp = NULL;
  int capi_tau_intent = 0;
  PyObject *tau_capi = Py_None;
  double *c = NULL;
  npy_intp c_Dims[2] = {-1, -1};
  const int c_Rank = 2;
  PyArrayObject *capi_c_tmp = NULL;
  int capi_c_intent = 0;
  PyObject *c_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int ibcbeg = 0;
  PyObject *ibcbeg_capi = Py_None;
  int ibcend = 0;
  PyObject *ibcend_capi = Py_None;
  static char *capi_kwlist[] = {"tau","c","ibcbeg","ibcend","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|O:aftan.cubspl",\
    capi_kwlist,&tau_capi,&c_capi,&ibcbeg_capi,&ibcend_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ibcbeg */
    f2py_success = int_from_pyobj(&ibcbeg,ibcbeg_capi,"aftan.cubspl() 3rd argument (ibcbeg) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ibcend */
    f2py_success = int_from_pyobj(&ibcend,ibcend_capi,"aftan.cubspl() 4th argument (ibcend) can't be converted to int");
  if (f2py_success) {
  /* Processing variable tau */
  ;
  capi_tau_intent |= F2PY_INTENT_IN;
  capi_tau_tmp = array_from_pyobj(NPY_DOUBLE,tau_Dims,tau_Rank,capi_tau_intent,tau_capi);
  if (capi_tau_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 1st argument `tau' of aftan.cubspl to C/Fortran array" );
  } else {
    tau = (double *)(PyArray_DATA(capi_tau_tmp));

  /* Processing variable n */
  if (n_capi == Py_None) n = len(tau); else
    f2py_success = int_from_pyobj(&n,n_capi,"aftan.cubspl() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(tau)>=n,"len(tau)>=n","1st keyword n","cubspl:n=%d",n) {
  /* Processing variable c */
  c_Dims[0]=4,c_Dims[1]=n;
  capi_c_intent |= F2PY_INTENT_IN;
  capi_c_tmp = array_from_pyobj(NPY_DOUBLE,c_Dims,c_Rank,capi_c_intent,c_capi);
  if (capi_c_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 2nd argument `c' of aftan.cubspl to C/Fortran array" );
  } else {
    c = (double *)(PyArray_DATA(capi_c_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(tau,c,&n,&ibcbeg,&ibcend);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_c_tmp!=c_capi) {
    Py_XDECREF(capi_c_tmp); }
  }  /*if (capi_c_tmp == NULL) ... else of c*/
  /* End of cleaning variable c */
  } /*CHECKSCALAR(len(tau)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_tau_tmp!=tau_capi) {
    Py_XDECREF(capi_tau_tmp); }
  }  /*if (capi_tau_tmp == NULL) ... else of tau*/
  /* End of cleaning variable tau */
  } /*if (f2py_success) of ibcend*/
  /* End of cleaning variable ibcend */
  } /*if (f2py_success) of ibcbeg*/
  /* End of cleaning variable ibcbeg */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of cubspl *******************************/

/********************************** phtovel **********************************/
static char doc_f2py_rout_aftan_phtovel[] = "\
phtovel(delta,ip,n,per,U,pha,prper,prvel,V,[npr])\n\nWrapper for ``phtovel``.\
\n\nParameters\n----------\n"
"delta : input float\n"
"ip : input int\n"
"n : input int\n"
"per : input rank-1 array('d') with bounds (100)\n"
"U : input rank-1 array('d') with bounds (100)\n"
"pha : input rank-1 array('d') with bounds (100)\n"
"prper : input rank-1 array('d') with bounds (npr)\n"
"prvel : input rank-1 array('d') with bounds (npr)\n"
"V : input rank-1 array('d') with bounds (100)\n"
"\nOther Parameters\n----------------\n"
"npr : input int, optional\n    Default: len(prper)";
/* extern void F_FUNC(phtovel,PHTOVEL)(double*,int*,int*,double*,double*,double*,int*,double*,double*,double*); */
static PyObject *f2py_rout_aftan_phtovel(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,double*,double*,double*,int*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double delta = 0;
  PyObject *delta_capi = Py_None;
  int ip = 0;
  PyObject *ip_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  double *per = NULL;
  npy_intp per_Dims[1] = {-1};
  const int per_Rank = 1;
  PyArrayObject *capi_per_tmp = NULL;
  int capi_per_intent = 0;
  PyObject *per_capi = Py_None;
  double *U = NULL;
  npy_intp U_Dims[1] = {-1};
  const int U_Rank = 1;
  PyArrayObject *capi_U_tmp = NULL;
  int capi_U_intent = 0;
  PyObject *U_capi = Py_None;
  double *pha = NULL;
  npy_intp pha_Dims[1] = {-1};
  const int pha_Rank = 1;
  PyArrayObject *capi_pha_tmp = NULL;
  int capi_pha_intent = 0;
  PyObject *pha_capi = Py_None;
  int npr = 0;
  PyObject *npr_capi = Py_None;
  double *prper = NULL;
  npy_intp prper_Dims[1] = {-1};
  const int prper_Rank = 1;
  PyArrayObject *capi_prper_tmp = NULL;
  int capi_prper_intent = 0;
  PyObject *prper_capi = Py_None;
  double *prvel = NULL;
  npy_intp prvel_Dims[1] = {-1};
  const int prvel_Rank = 1;
  PyArrayObject *capi_prvel_tmp = NULL;
  int capi_prvel_intent = 0;
  PyObject *prvel_capi = Py_None;
  double *V = NULL;
  npy_intp V_Dims[1] = {-1};
  const int V_Rank = 1;
  PyArrayObject *capi_V_tmp = NULL;
  int capi_V_intent = 0;
  PyObject *V_capi = Py_None;
  static char *capi_kwlist[] = {"delta","ip","n","per","U","pha","prper","prvel","V","npr",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|O:aftan.phtovel",\
    capi_kwlist,&delta_capi,&ip_capi,&n_capi,&per_capi,&U_capi,&pha_capi,&prper_capi,&prvel_capi,&V_capi,&npr_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ip */
    f2py_success = int_from_pyobj(&ip,ip_capi,"aftan.phtovel() 2nd argument (ip) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"aftan.phtovel() 3rd argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable delta */
    f2py_success = double_from_pyobj(&delta,delta_capi,"aftan.phtovel() 1st argument (delta) can't be converted to double");
  if (f2py_success) {
  /* Processing variable per */
  per_Dims[0]=100;
  capi_per_intent |= F2PY_INTENT_IN;
  capi_per_tmp = array_from_pyobj(NPY_DOUBLE,per_Dims,per_Rank,capi_per_intent,per_capi);
  if (capi_per_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 4th argument `per' of aftan.phtovel to C/Fortran array" );
  } else {
    per = (double *)(PyArray_DATA(capi_per_tmp));

  /* Processing variable U */
  U_Dims[0]=100;
  capi_U_intent |= F2PY_INTENT_IN;
  capi_U_tmp = array_from_pyobj(NPY_DOUBLE,U_Dims,U_Rank,capi_U_intent,U_capi);
  if (capi_U_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 5th argument `U' of aftan.phtovel to C/Fortran array" );
  } else {
    U = (double *)(PyArray_DATA(capi_U_tmp));

  /* Processing variable pha */
  pha_Dims[0]=100;
  capi_pha_intent |= F2PY_INTENT_IN;
  capi_pha_tmp = array_from_pyobj(NPY_DOUBLE,pha_Dims,pha_Rank,capi_pha_intent,pha_capi);
  if (capi_pha_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 6th argument `pha' of aftan.phtovel to C/Fortran array" );
  } else {
    pha = (double *)(PyArray_DATA(capi_pha_tmp));

  /* Processing variable prper */
  ;
  capi_prper_intent |= F2PY_INTENT_IN;
  capi_prper_tmp = array_from_pyobj(NPY_DOUBLE,prper_Dims,prper_Rank,capi_prper_intent,prper_capi);
  if (capi_prper_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 7th argument `prper' of aftan.phtovel to C/Fortran array" );
  } else {
    prper = (double *)(PyArray_DATA(capi_prper_tmp));

  /* Processing variable V */
  V_Dims[0]=100;
  capi_V_intent |= F2PY_INTENT_IN;
  capi_V_tmp = array_from_pyobj(NPY_DOUBLE,V_Dims,V_Rank,capi_V_intent,V_capi);
  if (capi_V_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 9th argument `V' of aftan.phtovel to C/Fortran array" );
  } else {
    V = (double *)(PyArray_DATA(capi_V_tmp));

  /* Processing variable npr */
  if (npr_capi == Py_None) npr = len(prper); else
    f2py_success = int_from_pyobj(&npr,npr_capi,"aftan.phtovel() 1st keyword (npr) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(prper)>=npr,"len(prper)>=npr","1st keyword npr","phtovel:npr=%d",npr) {
  /* Processing variable prvel */
  prvel_Dims[0]=npr;
  capi_prvel_intent |= F2PY_INTENT_IN;
  capi_prvel_tmp = array_from_pyobj(NPY_DOUBLE,prvel_Dims,prvel_Rank,capi_prvel_intent,prvel_capi);
  if (capi_prvel_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 8th argument `prvel' of aftan.phtovel to C/Fortran array" );
  } else {
    prvel = (double *)(PyArray_DATA(capi_prvel_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&delta,&ip,&n,per,U,pha,&npr,prper,prvel,V);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_prvel_tmp!=prvel_capi) {
    Py_XDECREF(capi_prvel_tmp); }
  }  /*if (capi_prvel_tmp == NULL) ... else of prvel*/
  /* End of cleaning variable prvel */
  } /*CHECKSCALAR(len(prper)>=npr)*/
  } /*if (f2py_success) of npr*/
  /* End of cleaning variable npr */
  if((PyObject *)capi_V_tmp!=V_capi) {
    Py_XDECREF(capi_V_tmp); }
  }  /*if (capi_V_tmp == NULL) ... else of V*/
  /* End of cleaning variable V */
  if((PyObject *)capi_prper_tmp!=prper_capi) {
    Py_XDECREF(capi_prper_tmp); }
  }  /*if (capi_prper_tmp == NULL) ... else of prper*/
  /* End of cleaning variable prper */
  if((PyObject *)capi_pha_tmp!=pha_capi) {
    Py_XDECREF(capi_pha_tmp); }
  }  /*if (capi_pha_tmp == NULL) ... else of pha*/
  /* End of cleaning variable pha */
  if((PyObject *)capi_U_tmp!=U_capi) {
    Py_XDECREF(capi_U_tmp); }
  }  /*if (capi_U_tmp == NULL) ... else of U*/
  /* End of cleaning variable U */
  if((PyObject *)capi_per_tmp!=per_capi) {
    Py_XDECREF(capi_per_tmp); }
  }  /*if (capi_per_tmp == NULL) ... else of per*/
  /* End of cleaning variable per */
  } /*if (f2py_success) of delta*/
  /* End of cleaning variable delta */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of ip*/
  /* End of cleaning variable ip */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of phtovel *******************************/

/********************************** pred_cur **********************************/
static char doc_f2py_rout_aftan_pred_cur[] = "\
pred_cur(ip,delta,om0,npred,pred,om1,Gt0)\n\nWrapper for ``pred_cur``.\
\n\nParameters\n----------\n"
"ip : input int\n"
"delta : input float\n"
"om0 : input float\n"
"npred : input int\n"
"pred : input rank-2 array('d') with bounds (500,2)\n"
"om1 : input float\n"
"Gt0 : input float";
/* extern void F_FUNC_US(pred_cur,PRED_CUR)(int*,double*,double*,int*,double*,double*,double*); */
static PyObject *f2py_rout_aftan_pred_cur(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,int*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int ip = 0;
  PyObject *ip_capi = Py_None;
  double delta = 0;
  PyObject *delta_capi = Py_None;
  double om0 = 0;
  PyObject *om0_capi = Py_None;
  int npred = 0;
  PyObject *npred_capi = Py_None;
  double *pred = NULL;
  npy_intp pred_Dims[2] = {-1, -1};
  const int pred_Rank = 2;
  PyArrayObject *capi_pred_tmp = NULL;
  int capi_pred_intent = 0;
  PyObject *pred_capi = Py_None;
  double om1 = 0;
  PyObject *om1_capi = Py_None;
  double Gt0 = 0;
  PyObject *Gt0_capi = Py_None;
  static char *capi_kwlist[] = {"ip","delta","om0","npred","pred","om1","Gt0",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:aftan.pred_cur",\
    capi_kwlist,&ip_capi,&delta_capi,&om0_capi,&npred_capi,&pred_capi,&om1_capi,&Gt0_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ip */
    f2py_success = int_from_pyobj(&ip,ip_capi,"aftan.pred_cur() 1st argument (ip) can't be converted to int");
  if (f2py_success) {
  /* Processing variable npred */
    f2py_success = int_from_pyobj(&npred,npred_capi,"aftan.pred_cur() 4th argument (npred) can't be converted to int");
  if (f2py_success) {
  /* Processing variable delta */
    f2py_success = double_from_pyobj(&delta,delta_capi,"aftan.pred_cur() 2nd argument (delta) can't be converted to double");
  if (f2py_success) {
  /* Processing variable om0 */
    f2py_success = double_from_pyobj(&om0,om0_capi,"aftan.pred_cur() 3rd argument (om0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable om1 */
    f2py_success = double_from_pyobj(&om1,om1_capi,"aftan.pred_cur() 6th argument (om1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable Gt0 */
    f2py_success = double_from_pyobj(&Gt0,Gt0_capi,"aftan.pred_cur() 7th argument (Gt0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable pred */
  pred_Dims[0]=500,pred_Dims[1]=2;
  capi_pred_intent |= F2PY_INTENT_IN;
  capi_pred_tmp = array_from_pyobj(NPY_DOUBLE,pred_Dims,pred_Rank,capi_pred_intent,pred_capi);
  if (capi_pred_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 5th argument `pred' of aftan.pred_cur to C/Fortran array" );
  } else {
    pred = (double *)(PyArray_DATA(capi_pred_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&ip,&delta,&om0,&npred,pred,&om1,&Gt0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_pred_tmp!=pred_capi) {
    Py_XDECREF(capi_pred_tmp); }
  }  /*if (capi_pred_tmp == NULL) ... else of pred*/
  /* End of cleaning variable pred */
  } /*if (f2py_success) of Gt0*/
  /* End of cleaning variable Gt0 */
  } /*if (f2py_success) of om1*/
  /* End of cleaning variable om1 */
  } /*if (f2py_success) of om0*/
  /* End of cleaning variable om0 */
  } /*if (f2py_success) of delta*/
  /* End of cleaning variable delta */
  } /*if (f2py_success) of npred*/
  /* End of cleaning variable npred */
  } /*if (f2py_success) of ip*/
  /* End of cleaning variable ip */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of pred_cur ******************************/

/*********************************** taper ***********************************/
static char doc_f2py_rout_aftan_taper[] = "\
taper(nb,ne,n,seis,ntapb,ntape,ss,ncorr)\n\nWrapper for ``taper``.\
\n\nParameters\n----------\n"
"nb : input int\n"
"ne : input int\n"
"n : input int\n"
"seis : input rank-1 array('f') with bounds (32768)\n"
"ntapb : input int\n"
"ntape : input int\n"
"ss : input rank-1 array('D') with bounds (32768)\n"
"ncorr : input int";
/* extern void F_FUNC(taper,TAPER)(int*,int*,int*,float*,int*,int*,complex_double*,int*); */
static PyObject *f2py_rout_aftan_taper(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,float*,int*,int*,complex_double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nb = 0;
  PyObject *nb_capi = Py_None;
  int ne = 0;
  PyObject *ne_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  float *seis = NULL;
  npy_intp seis_Dims[1] = {-1};
  const int seis_Rank = 1;
  PyArrayObject *capi_seis_tmp = NULL;
  int capi_seis_intent = 0;
  PyObject *seis_capi = Py_None;
  int ntapb = 0;
  PyObject *ntapb_capi = Py_None;
  int ntape = 0;
  PyObject *ntape_capi = Py_None;
  complex_double *ss = NULL;
  npy_intp ss_Dims[1] = {-1};
  const int ss_Rank = 1;
  PyArrayObject *capi_ss_tmp = NULL;
  int capi_ss_intent = 0;
  PyObject *ss_capi = Py_None;
  int ncorr = 0;
  PyObject *ncorr_capi = Py_None;
  static char *capi_kwlist[] = {"nb","ne","n","seis","ntapb","ntape","ss","ncorr",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO:aftan.taper",\
    capi_kwlist,&nb_capi,&ne_capi,&n_capi,&seis_capi,&ntapb_capi,&ntape_capi,&ss_capi,&ncorr_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable nb */
    f2py_success = int_from_pyobj(&nb,nb_capi,"aftan.taper() 1st argument (nb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ne */
    f2py_success = int_from_pyobj(&ne,ne_capi,"aftan.taper() 2nd argument (ne) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"aftan.taper() 3rd argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ntapb */
    f2py_success = int_from_pyobj(&ntapb,ntapb_capi,"aftan.taper() 5th argument (ntapb) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ntape */
    f2py_success = int_from_pyobj(&ntape,ntape_capi,"aftan.taper() 6th argument (ntape) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ncorr */
    f2py_success = int_from_pyobj(&ncorr,ncorr_capi,"aftan.taper() 8th argument (ncorr) can't be converted to int");
  if (f2py_success) {
  /* Processing variable seis */
  seis_Dims[0]=32768;
  capi_seis_intent |= F2PY_INTENT_IN;
  capi_seis_tmp = array_from_pyobj(NPY_FLOAT,seis_Dims,seis_Rank,capi_seis_intent,seis_capi);
  if (capi_seis_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 4th argument `seis' of aftan.taper to C/Fortran array" );
  } else {
    seis = (float *)(PyArray_DATA(capi_seis_tmp));

  /* Processing variable ss */
  ss_Dims[0]=32768;
  capi_ss_intent |= F2PY_INTENT_IN;
  capi_ss_tmp = array_from_pyobj(NPY_CDOUBLE,ss_Dims,ss_Rank,capi_ss_intent,ss_capi);
  if (capi_ss_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 7th argument `ss' of aftan.taper to C/Fortran array" );
  } else {
    ss = (complex_double *)(PyArray_DATA(capi_ss_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nb,&ne,&n,seis,&ntapb,&ntape,ss,&ncorr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_ss_tmp!=ss_capi) {
    Py_XDECREF(capi_ss_tmp); }
  }  /*if (capi_ss_tmp == NULL) ... else of ss*/
  /* End of cleaning variable ss */
  if((PyObject *)capi_seis_tmp!=seis_capi) {
    Py_XDECREF(capi_seis_tmp); }
  }  /*if (capi_seis_tmp == NULL) ... else of seis*/
  /* End of cleaning variable seis */
  } /*if (f2py_success) of ncorr*/
  /* End of cleaning variable ncorr */
  } /*if (f2py_success) of ntape*/
  /* End of cleaning variable ntape */
  } /*if (f2py_success) of ntapb*/
  /* End of cleaning variable ntapb */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of ne*/
  /* End of cleaning variable ne */
  } /*if (f2py_success) of nb*/
  /* End of cleaning variable nb */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of taper ********************************/

/*********************************** tapers ***********************************/
static char doc_f2py_rout_aftan_tapers[] = "\
tapers(omb,ome,dom,alpha,omstart,inds,inde,omdom,ampdom,[ns])\n\nWrapper for ``tapers``.\
\n\nParameters\n----------\n"
"omb : input float\n"
"ome : input float\n"
"dom : input float\n"
"alpha : input float\n"
"omstart : input float\n"
"inds : input int\n"
"inde : input int\n"
"omdom : input rank-1 array('d') with bounds (ns)\n"
"ampdom : input rank-1 array('d') with bounds (ns)\n"
"\nOther Parameters\n----------------\n"
"ns : input int, optional\n    Default: len(omdom)";
/* extern void F_FUNC(tapers,TAPERS)(double*,double*,double*,double*,int*,double*,int*,int*,double*,double*); */
static PyObject *f2py_rout_aftan_tapers(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,double*,int*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double omb = 0;
  PyObject *omb_capi = Py_None;
  double ome = 0;
  PyObject *ome_capi = Py_None;
  double dom = 0;
  PyObject *dom_capi = Py_None;
  double alpha = 0;
  PyObject *alpha_capi = Py_None;
  int ns = 0;
  PyObject *ns_capi = Py_None;
  double omstart = 0;
  PyObject *omstart_capi = Py_None;
  int inds = 0;
  PyObject *inds_capi = Py_None;
  int inde = 0;
  PyObject *inde_capi = Py_None;
  double *omdom = NULL;
  npy_intp omdom_Dims[1] = {-1};
  const int omdom_Rank = 1;
  PyArrayObject *capi_omdom_tmp = NULL;
  int capi_omdom_intent = 0;
  PyObject *omdom_capi = Py_None;
  double *ampdom = NULL;
  npy_intp ampdom_Dims[1] = {-1};
  const int ampdom_Rank = 1;
  PyArrayObject *capi_ampdom_tmp = NULL;
  int capi_ampdom_intent = 0;
  PyObject *ampdom_capi = Py_None;
  static char *capi_kwlist[] = {"omb","ome","dom","alpha","omstart","inds","inde","omdom","ampdom","ns",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|O:aftan.tapers",\
    capi_kwlist,&omb_capi,&ome_capi,&dom_capi,&alpha_capi,&omstart_capi,&inds_capi,&inde_capi,&omdom_capi,&ampdom_capi,&ns_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable inds */
    f2py_success = int_from_pyobj(&inds,inds_capi,"aftan.tapers() 6th argument (inds) can't be converted to int");
  if (f2py_success) {
  /* Processing variable inde */
    f2py_success = int_from_pyobj(&inde,inde_capi,"aftan.tapers() 7th argument (inde) can't be converted to int");
  if (f2py_success) {
  /* Processing variable omb */
    f2py_success = double_from_pyobj(&omb,omb_capi,"aftan.tapers() 1st argument (omb) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ome */
    f2py_success = double_from_pyobj(&ome,ome_capi,"aftan.tapers() 2nd argument (ome) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dom */
    f2py_success = double_from_pyobj(&dom,dom_capi,"aftan.tapers() 3rd argument (dom) can't be converted to double");
  if (f2py_success) {
  /* Processing variable alpha */
    f2py_success = double_from_pyobj(&alpha,alpha_capi,"aftan.tapers() 4th argument (alpha) can't be converted to double");
  if (f2py_success) {
  /* Processing variable omstart */
    f2py_success = double_from_pyobj(&omstart,omstart_capi,"aftan.tapers() 5th argument (omstart) can't be converted to double");
  if (f2py_success) {
  /* Processing variable omdom */
  ;
  capi_omdom_intent |= F2PY_INTENT_IN;
  capi_omdom_tmp = array_from_pyobj(NPY_DOUBLE,omdom_Dims,omdom_Rank,capi_omdom_intent,omdom_capi);
  if (capi_omdom_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 8th argument `omdom' of aftan.tapers to C/Fortran array" );
  } else {
    omdom = (double *)(PyArray_DATA(capi_omdom_tmp));

  /* Processing variable ns */
  if (ns_capi == Py_None) ns = len(omdom); else
    f2py_success = int_from_pyobj(&ns,ns_capi,"aftan.tapers() 1st keyword (ns) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(omdom)>=ns,"len(omdom)>=ns","1st keyword ns","tapers:ns=%d",ns) {
  /* Processing variable ampdom */
  ampdom_Dims[0]=ns;
  capi_ampdom_intent |= F2PY_INTENT_IN;
  capi_ampdom_tmp = array_from_pyobj(NPY_DOUBLE,ampdom_Dims,ampdom_Rank,capi_ampdom_intent,ampdom_capi);
  if (capi_ampdom_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 9th argument `ampdom' of aftan.tapers to C/Fortran array" );
  } else {
    ampdom = (double *)(PyArray_DATA(capi_ampdom_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&omb,&ome,&dom,&alpha,&ns,&omstart,&inds,&inde,omdom,ampdom);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_ampdom_tmp!=ampdom_capi) {
    Py_XDECREF(capi_ampdom_tmp); }
  }  /*if (capi_ampdom_tmp == NULL) ... else of ampdom*/
  /* End of cleaning variable ampdom */
  } /*CHECKSCALAR(len(omdom)>=ns)*/
  } /*if (f2py_success) of ns*/
  /* End of cleaning variable ns */
  if((PyObject *)capi_omdom_tmp!=omdom_capi) {
    Py_XDECREF(capi_omdom_tmp); }
  }  /*if (capi_omdom_tmp == NULL) ... else of omdom*/
  /* End of cleaning variable omdom */
  } /*if (f2py_success) of omstart*/
  /* End of cleaning variable omstart */
  } /*if (f2py_success) of alpha*/
  /* End of cleaning variable alpha */
  } /*if (f2py_success) of dom*/
  /* End of cleaning variable dom */
  } /*if (f2py_success) of ome*/
  /* End of cleaning variable ome */
  } /*if (f2py_success) of omb*/
  /* End of cleaning variable omb */
  } /*if (f2py_success) of inde*/
  /* End of cleaning variable inde */
  } /*if (f2py_success) of inds*/
  /* End of cleaning variable inds */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of tapers *******************************/

/*********************************** tgauss ***********************************/
static char doc_f2py_rout_aftan_tgauss[] = "\
tgauss(fsnr,gt0,t0,dw,dt,fmatch,seis,ss,cuttype,[n])\n\nWrapper for ``tgauss``.\
\n\nParameters\n----------\n"
"fsnr : input float\n"
"gt0 : input float\n"
"t0 : input float\n"
"dw : input float\n"
"dt : input float\n"
"fmatch : input float\n"
"seis : input rank-1 array('D') with bounds (n)\n"
"ss : input rank-1 array('D') with bounds (n)\n"
"cuttype : input int\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(seis)";
/* extern void F_FUNC(tgauss,TGAUSS)(double*,double*,double*,double*,double*,int*,double*,complex_double*,complex_double*,int*); */
static PyObject *f2py_rout_aftan_tgauss(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,int*,double*,complex_double*,complex_double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double fsnr = 0;
  PyObject *fsnr_capi = Py_None;
  double gt0 = 0;
  PyObject *gt0_capi = Py_None;
  double t0 = 0;
  PyObject *t0_capi = Py_None;
  double dw = 0;
  PyObject *dw_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  double fmatch = 0;
  PyObject *fmatch_capi = Py_None;
  complex_double *seis = NULL;
  npy_intp seis_Dims[1] = {-1};
  const int seis_Rank = 1;
  PyArrayObject *capi_seis_tmp = NULL;
  int capi_seis_intent = 0;
  PyObject *seis_capi = Py_None;
  complex_double *ss = NULL;
  npy_intp ss_Dims[1] = {-1};
  const int ss_Rank = 1;
  PyArrayObject *capi_ss_tmp = NULL;
  int capi_ss_intent = 0;
  PyObject *ss_capi = Py_None;
  int cuttype = 0;
  PyObject *cuttype_capi = Py_None;
  static char *capi_kwlist[] = {"fsnr","gt0","t0","dw","dt","fmatch","seis","ss","cuttype","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|O:aftan.tgauss",\
    capi_kwlist,&fsnr_capi,&gt0_capi,&t0_capi,&dw_capi,&dt_capi,&fmatch_capi,&seis_capi,&ss_capi,&cuttype_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable cuttype */
    f2py_success = int_from_pyobj(&cuttype,cuttype_capi,"aftan.tgauss() 9th argument (cuttype) can't be converted to int");
  if (f2py_success) {
  /* Processing variable seis */
  ;
  capi_seis_intent |= F2PY_INTENT_IN;
  capi_seis_tmp = array_from_pyobj(NPY_CDOUBLE,seis_Dims,seis_Rank,capi_seis_intent,seis_capi);
  if (capi_seis_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 7th argument `seis' of aftan.tgauss to C/Fortran array" );
  } else {
    seis = (complex_double *)(PyArray_DATA(capi_seis_tmp));

  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"aftan.tgauss() 5th argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gt0 */
    f2py_success = double_from_pyobj(&gt0,gt0_capi,"aftan.tgauss() 2nd argument (gt0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t0 */
    f2py_success = double_from_pyobj(&t0,t0_capi,"aftan.tgauss() 3rd argument (t0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dw */
    f2py_success = double_from_pyobj(&dw,dw_capi,"aftan.tgauss() 4th argument (dw) can't be converted to double");
  if (f2py_success) {
  /* Processing variable fsnr */
    f2py_success = double_from_pyobj(&fsnr,fsnr_capi,"aftan.tgauss() 1st argument (fsnr) can't be converted to double");
  if (f2py_success) {
  /* Processing variable fmatch */
    f2py_success = double_from_pyobj(&fmatch,fmatch_capi,"aftan.tgauss() 6th argument (fmatch) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(seis); else
    f2py_success = int_from_pyobj(&n,n_capi,"aftan.tgauss() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(seis)>=n,"len(seis)>=n","1st keyword n","tgauss:n=%d",n) {
  /* Processing variable ss */
  ss_Dims[0]=n;
  capi_ss_intent |= F2PY_INTENT_IN;
  capi_ss_tmp = array_from_pyobj(NPY_CDOUBLE,ss_Dims,ss_Rank,capi_ss_intent,ss_capi);
  if (capi_ss_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 8th argument `ss' of aftan.tgauss to C/Fortran array" );
  } else {
    ss = (complex_double *)(PyArray_DATA(capi_ss_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&fsnr,&gt0,&t0,&dw,&dt,&n,&fmatch,seis,ss,&cuttype);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_ss_tmp!=ss_capi) {
    Py_XDECREF(capi_ss_tmp); }
  }  /*if (capi_ss_tmp == NULL) ... else of ss*/
  /* End of cleaning variable ss */
  } /*CHECKSCALAR(len(seis)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of fmatch*/
  /* End of cleaning variable fmatch */
  } /*if (f2py_success) of fsnr*/
  /* End of cleaning variable fsnr */
  } /*if (f2py_success) of dw*/
  /* End of cleaning variable dw */
  } /*if (f2py_success) of t0*/
  /* End of cleaning variable t0 */
  } /*if (f2py_success) of gt0*/
  /* End of cleaning variable gt0 */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  if((PyObject *)capi_seis_tmp!=seis_capi) {
    Py_XDECREF(capi_seis_tmp); }
  }  /*if (capi_seis_tmp == NULL) ... else of seis*/
  /* End of cleaning variable seis */
  } /*if (f2py_success) of cuttype*/
  /* End of cleaning variable cuttype */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of tgauss *******************************/

/********************************** trigger **********************************/
static char doc_f2py_rout_aftan_trigger[] = "\
trigger(grvel,per,nf,tresh,trig,ftrig,ierr)\n\nWrapper for ``trigger``.\
\n\nParameters\n----------\n"
"grvel : input rank-1 array('d') with bounds (100)\n"
"per : input rank-1 array('d') with bounds (100)\n"
"nf : input int\n"
"tresh : input float\n"
"trig : input rank-1 array('d') with bounds (100)\n"
"ftrig : input rank-1 array('d') with bounds (100)\n"
"ierr : input int";
/* extern void F_FUNC(trigger,TRIGGER)(double*,double*,int*,double*,double*,double*,int*); */
static PyObject *f2py_rout_aftan_trigger(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *grvel = NULL;
  npy_intp grvel_Dims[1] = {-1};
  const int grvel_Rank = 1;
  PyArrayObject *capi_grvel_tmp = NULL;
  int capi_grvel_intent = 0;
  PyObject *grvel_capi = Py_None;
  double *per = NULL;
  npy_intp per_Dims[1] = {-1};
  const int per_Rank = 1;
  PyArrayObject *capi_per_tmp = NULL;
  int capi_per_intent = 0;
  PyObject *per_capi = Py_None;
  int nf = 0;
  PyObject *nf_capi = Py_None;
  double tresh = 0;
  PyObject *tresh_capi = Py_None;
  double *trig = NULL;
  npy_intp trig_Dims[1] = {-1};
  const int trig_Rank = 1;
  PyArrayObject *capi_trig_tmp = NULL;
  int capi_trig_intent = 0;
  PyObject *trig_capi = Py_None;
  double *ftrig = NULL;
  npy_intp ftrig_Dims[1] = {-1};
  const int ftrig_Rank = 1;
  PyArrayObject *capi_ftrig_tmp = NULL;
  int capi_ftrig_intent = 0;
  PyObject *ftrig_capi = Py_None;
  int ierr = 0;
  PyObject *ierr_capi = Py_None;
  static char *capi_kwlist[] = {"grvel","per","nf","tresh","trig","ftrig","ierr",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:aftan.trigger",\
    capi_kwlist,&grvel_capi,&per_capi,&nf_capi,&tresh_capi,&trig_capi,&ftrig_capi,&ierr_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable nf */
    f2py_success = int_from_pyobj(&nf,nf_capi,"aftan.trigger() 3rd argument (nf) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ierr */
    f2py_success = int_from_pyobj(&ierr,ierr_capi,"aftan.trigger() 7th argument (ierr) can't be converted to int");
  if (f2py_success) {
  /* Processing variable tresh */
    f2py_success = double_from_pyobj(&tresh,tresh_capi,"aftan.trigger() 4th argument (tresh) can't be converted to double");
  if (f2py_success) {
  /* Processing variable grvel */
  grvel_Dims[0]=100;
  capi_grvel_intent |= F2PY_INTENT_IN;
  capi_grvel_tmp = array_from_pyobj(NPY_DOUBLE,grvel_Dims,grvel_Rank,capi_grvel_intent,grvel_capi);
  if (capi_grvel_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 1st argument `grvel' of aftan.trigger to C/Fortran array" );
  } else {
    grvel = (double *)(PyArray_DATA(capi_grvel_tmp));

  /* Processing variable per */
  per_Dims[0]=100;
  capi_per_intent |= F2PY_INTENT_IN;
  capi_per_tmp = array_from_pyobj(NPY_DOUBLE,per_Dims,per_Rank,capi_per_intent,per_capi);
  if (capi_per_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 2nd argument `per' of aftan.trigger to C/Fortran array" );
  } else {
    per = (double *)(PyArray_DATA(capi_per_tmp));

  /* Processing variable trig */
  trig_Dims[0]=100;
  capi_trig_intent |= F2PY_INTENT_IN;
  capi_trig_tmp = array_from_pyobj(NPY_DOUBLE,trig_Dims,trig_Rank,capi_trig_intent,trig_capi);
  if (capi_trig_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 5th argument `trig' of aftan.trigger to C/Fortran array" );
  } else {
    trig = (double *)(PyArray_DATA(capi_trig_tmp));

  /* Processing variable ftrig */
  ftrig_Dims[0]=100;
  capi_ftrig_intent |= F2PY_INTENT_IN;
  capi_ftrig_tmp = array_from_pyobj(NPY_DOUBLE,ftrig_Dims,ftrig_Rank,capi_ftrig_intent,ftrig_capi);
  if (capi_ftrig_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(aftan_error,"failed in converting 6th argument `ftrig' of aftan.trigger to C/Fortran array" );
  } else {
    ftrig = (double *)(PyArray_DATA(capi_ftrig_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(grvel,per,&nf,&tresh,trig,ftrig,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_ftrig_tmp!=ftrig_capi) {
    Py_XDECREF(capi_ftrig_tmp); }
  }  /*if (capi_ftrig_tmp == NULL) ... else of ftrig*/
  /* End of cleaning variable ftrig */
  if((PyObject *)capi_trig_tmp!=trig_capi) {
    Py_XDECREF(capi_trig_tmp); }
  }  /*if (capi_trig_tmp == NULL) ... else of trig*/
  /* End of cleaning variable trig */
  if((PyObject *)capi_per_tmp!=per_capi) {
    Py_XDECREF(capi_per_tmp); }
  }  /*if (capi_per_tmp == NULL) ... else of per*/
  /* End of cleaning variable per */
  if((PyObject *)capi_grvel_tmp!=grvel_capi) {
    Py_XDECREF(capi_grvel_tmp); }
  }  /*if (capi_grvel_tmp == NULL) ... else of grvel*/
  /* End of cleaning variable grvel */
  } /*if (f2py_success) of tresh*/
  /* End of cleaning variable tresh */
  } /*if (f2py_success) of ierr*/
  /* End of cleaning variable ierr */
  } /*if (f2py_success) of nf*/
  /* End of cleaning variable nf */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of trigger *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_mspdat_def[] = {
  {"nn",1,{{10}},NPY_INT},
  {"ndim",1,{{10}},NPY_INT},
  {"xx",2,{{1001,10}},NPY_DOUBLE},
  {"sc",3,{{4,1001,10}},NPY_DOUBLE},
  {"scc",3,{{5,1001,10}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_mspdat(char *nn,char *ndim,char *xx,char *sc,char *scc) {
  int i_f2py=0;
  f2py_mspdat_def[i_f2py++].data = nn;
  f2py_mspdat_def[i_f2py++].data = ndim;
  f2py_mspdat_def[i_f2py++].data = xx;
  f2py_mspdat_def[i_f2py++].data = sc;
  f2py_mspdat_def[i_f2py++].data = scc;
}
extern void F_FUNC(f2pyinitmspdat,F2PYINITMSPDAT)(void(*)(char*,char*,char*,char*,char*));
static void f2py_init_mspdat(void) {
  F_FUNC(f2pyinitmspdat,F2PYINITMSPDAT)(f2py_setup_mspdat);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"aftanipg",-1,{{-1}},0,(char *)F_FUNC(aftanipg,AFTANIPG),(f2py_init_func)f2py_rout_aftan_aftanipg,doc_f2py_rout_aftan_aftanipg},
  {"unknown_subroutine",-1,{{-1}},0,(char *)F_FUNC_US(unknown_subroutine,UNKNOWN_SUBROUTINE),(f2py_init_func)f2py_rout_aftan_unknown_subroutine,doc_f2py_rout_aftan_unknown_subroutine},
  {"fmax",-1,{{-1}},0,(char *)F_FUNC(fmax,FMAX),(f2py_init_func)f2py_rout_aftan_fmax,doc_f2py_rout_aftan_fmax},
  {"ftfilt",-1,{{-1}},0,(char *)F_FUNC(ftfilt,FTFILT),(f2py_init_func)f2py_rout_aftan_ftfilt,doc_f2py_rout_aftan_ftfilt},
  {"mspline",-1,{{-1}},0,(char *)F_FUNC(mspline,MSPLINE),(f2py_init_func)f2py_rout_aftan_mspline,doc_f2py_rout_aftan_mspline},
  {"msplint",-1,{{-1}},0,(char *)F_FUNC(msplint,MSPLINT),(f2py_init_func)f2py_rout_aftan_msplint,doc_f2py_rout_aftan_msplint},
  {"msplder",-1,{{-1}},0,(char *)F_FUNC(msplder,MSPLDER),(f2py_init_func)f2py_rout_aftan_msplder,doc_f2py_rout_aftan_msplder},
  {"cubspl",-1,{{-1}},0,(char *)F_FUNC(cubspl,CUBSPL),(f2py_init_func)f2py_rout_aftan_cubspl,doc_f2py_rout_aftan_cubspl},
  {"phtovel",-1,{{-1}},0,(char *)F_FUNC(phtovel,PHTOVEL),(f2py_init_func)f2py_rout_aftan_phtovel,doc_f2py_rout_aftan_phtovel},
  {"pred_cur",-1,{{-1}},0,(char *)F_FUNC_US(pred_cur,PRED_CUR),(f2py_init_func)f2py_rout_aftan_pred_cur,doc_f2py_rout_aftan_pred_cur},
  {"taper",-1,{{-1}},0,(char *)F_FUNC(taper,TAPER),(f2py_init_func)f2py_rout_aftan_taper,doc_f2py_rout_aftan_taper},
  {"tapers",-1,{{-1}},0,(char *)F_FUNC(tapers,TAPERS),(f2py_init_func)f2py_rout_aftan_tapers,doc_f2py_rout_aftan_tapers},
  {"tgauss",-1,{{-1}},0,(char *)F_FUNC(tgauss,TGAUSS),(f2py_init_func)f2py_rout_aftan_tgauss,doc_f2py_rout_aftan_tgauss},
  {"trigger",-1,{{-1}},0,(char *)F_FUNC(trigger,TRIGGER),(f2py_init_func)f2py_rout_aftan_trigger,doc_f2py_rout_aftan_trigger},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "aftan",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_aftan(void) {
#else
#define RETVAL
PyMODINIT_FUNC initaftan(void) {
#endif
  int i;
  PyObject *m,*d, *s, *tmp;
#if PY_VERSION_HEX >= 0x03000000
  m = aftan_module = PyModule_Create(&moduledef);
#else
  m = aftan_module = Py_InitModule("aftan", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module aftan (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'aftan' is auto-generated with f2py (version:2).\nFunctions:\n"
"  aftanipg(piover4,n,sei,t0,dt,delta,vmin,vmax,tmin,tmax,tresh,ffact,perc,npoints,taperl,nfin,fsnr,fmatch,npred,cuttype,phprper,phprvel,seiout,nfout1,arr1,nfout2,arr2,tamp,nrow,ncol,amp,ierr,nphpr=len(phprper))\n"
"  unknown_subroutine()\n"
"  fmax(am1,am2,am3,ph1,ph2,ph3,om,dt,t,dph,tm,ph,piover4)\n"
"  ftfilt(alpha,om0,dom,n,a,fs,b)\n"
"  mspline(ip,n,x,y,ind1,d1,ind2,d2)\n"
"  msplint(ip,sa,sb,sint,ierr)\n"
"  msplder(ip,xt,s,sd,sdd,ierr)\n"
"  cubspl(tau,c,ibcbeg,ibcend,n=len(tau))\n"
"  phtovel(delta,ip,n,per,U,pha,prper,prvel,V,npr=len(prper))\n"
"  pred_cur(ip,delta,om0,npred,pred,om1,Gt0)\n"
"  taper(nb,ne,n,seis,ntapb,ntape,ss,ncorr)\n"
"  tapers(omb,ome,dom,alpha,omstart,inds,inde,omdom,ampdom,ns=len(omdom))\n"
"  tgauss(fsnr,gt0,t0,dw,dt,fmatch,seis,ss,cuttype,n=len(seis))\n"
"  trigger(grvel,per,nf,tresh,trig,ftrig,ierr)\n"
"COMMON blocks:\n""  /mspdat/ nn(10),ndim(10),xx(1001,10),sc(4,1001,10),scc(5,1001,10)\n"".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  aftan_error = PyErr_NewException ("aftan.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_aftan_error", aftan_error);
  Py_DECREF(aftan_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }














/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  tmp = PyFortranObject_New(f2py_mspdat_def,f2py_init_mspdat);
  F2PyDict_SetItemString(d, "mspdat", tmp);
  Py_DECREF(tmp);
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"aftan");
#endif
  return RETVAL;
}
#ifdef __cplusplus
}
#endif
